# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MaviccPRP@web.studio
email: info@webstudio-richter.de
description: > # this means to ignore newlines until "baseurl:"
  A place for CSS, HTML and Machine Learning enthusiasts
baseurl: "" # the subpath of your site, e.g. /blog
url: https://maviccprp.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: webstudio_R
github_username:  MaviccPRP
facebook_username: webstudio.richter
google_plus_username: 105357986131693436330?rel=author
pinterest_username: webstudioR
youtube_username: user/webstudioRichter
disqus: https-maviccprp-github-io

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag  
exclude:
  - Gemfile
  - Gemfile.lock
